### ISSUE TITLE
Ending parenthesis missing on json callback

### ISSUE THREAD

**Issue by gitlucen** [edgedalmacio/phisix#17] opened 2016-05-22 02:51 UTC
When using a callback function for json format request, the last parenthesis is missing
![a](https://cloud.githubusercontent.com/assets/17109193/15451867/27914288-200b-11e6-94f8-77c3d0c1f867.JPG)

**Comment by edgedalmacio** [comment] 2020-07-21 16:08
Duplicate of #6

**Closed** 2020-07-21 16:08 UTC
