### ISSUE TITLE
PSE & PSEi symbol are the same

### ISSUE THREAD

**Issue by fur-elyse** [edgedalmacio/phisix#101] opened 2020-07-17 07:05 UTC
Hi Edge,

Hope you're doing well. I love your work on this! Please keep going.

I noticed that the symbol for both PSE and PSEi in your json file is both labeled as PSE.
{"name":**_"PSE"_**,"price":{"currency":"PHP","amount":160.50},"percent_change":0.31,"volume":2160,"symbol":**_"PSE"_**}
{"name":_**"PSEi"**_,"price":{"currency":"PHP","amount":-58.9100},"percent_change":-0.96,"volume":6088,"symbol":**_"PSE"_**}

So when I'm trying to pull the specific page (http://phisix-api3.appspot.com/stocks/PSE.json), it returns the PSE price of the day rather than the psei.

**Comment by edgedalmacio** [comment] 2020-07-19 14:37
Duplicate of #22

**Closed** 2020-07-19 15:16 UTC
